core/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication.urls, kendaraan.urls, lokasi.urls, batch_pengiriman.urls, pesanansumberdaya.urls, stokfaskes.urls, faskes.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(authentication.urls)),
    path('',include(kendaraan.urls)),
    path('',include(lokasi.urls)),
    path('',include(batch_pengiriman.urls)),
    path('',include(pesanansumberdaya.urls)),
    path('',include(stokfaskes.urls)),
    path('',include(faskes.urls)),
]

kendaraan/urls.py
from django.urls import path
from .views import *

app_name = 'kendaraan'

urlpatterns = [
	path('kendaraan/add', add_kendaraan, name='add_kendaraan'),
	path('kendaraan/read', read_kendaraan, name='read_kendaraan'),
	path('kendaraan/update/<str:my_id>', update_kendaraan, name='update'),
	path('kendaraan/delete/<str:my_id>', delete_kendaraan, name='delete'),
]

pesanansumberdaya/urls.py
from django.urls import path
from .views import *

app_name = 'pesanansumberdaya'

urlpatterns = [
	path('pesanansumberdaya/create', create_pesanansumberdaya, name='create_pesanansumberdaya'),
	path('pesanansumberdaya/read', read_pesanansumberdaya, name='read_pesanansumberdaya'),
	path('pesanansumberdaya/update/<str:my_id>', update_pesanansumberdaya, name='update'),
    path('pesanansumberdaya/detail/<str:my_id>', detail_pesanansumberdaya, name='detail'),
	path('pesanansumberdaya/delete/<str:my_id>', delete_pesanansumberdaya, name='delete'),
	path('supplier/get-item-by-supplier', get_item_by_supplier, name='get-item-by-supplier'),
]

pesanansumberdaya/models.py
from django.db import models

# Create your models here.

pesanansumberdaya/forms.py
from django import forms
from django.db import connection
from collections import namedtuple

initial = []

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def get_supplier():
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT * from supplier WHERE username IN (SELECT username_supplier FROM item_sumber_daya);")
        hasil = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
    
    result = [tuple([hasil[i].username , hasil[i].nama_organisasi]) for i in range(len(hasil))]
    return result

def get_initial():
    result = [tuple([i, i]) for i in initial]
    return result


class addDaftarItemForm(forms.Form):

    no_urut = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Kendaraan',
        'type': 'int',
        'required': True,
        'readonly': True,
    }))

    supplier = forms.CharField(label="supplier", widget=forms.Select(choices=get_supplier()))

    kode_item = forms.CharField(label="kode_item", widget=forms.Select(choices=get_initial()))

    jumlah_item = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'jumlah_item',
        'type': 'int',
        'required': True,
    }))

pesanansumberdaya/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import *
import sys
import datetime
import django

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def generate_id_pesanan_sumber_daya():
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT nomor FROM transaksi_sumber_daya ORDER BY nomor DESC LIMIT 1;")
        last_id = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        if len(last_id) == 0:
            return 1
        
        number = int(last_id[0].nomor) + 1

    return number


def get_item_by_supplier(request):
    supplier_username = request.GET.get('supplier')
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT * from item_sumber_daya WHERE username_supplier = '{}';".format(supplier_username))
        hasil = namedtuplefetchall(c)
        c.execute("Set search_path to public;")

    print(supplier_username)
    return render(request, 'ajax_updateitembysupplier.html', {'items': hasil})

def create_pesanansumberdaya(request):
    if request.method == 'POST':
        form = addDaftarItemForm(request.POST)
        if form.is_valid():
            no_urut = form.cleaned_data['no_urut']
            supplier = form.cleaned_data['supplier']
            kode_item = form.cleaned_data['kode_item']
            jumlah_item = form.cleaned_data['jumlah_item']

            response = {}
            
            try:
                with connection.cursor() as c:
                    if int(no_urut) == 1:
                        nomor_pesanan = generate_id_pesanan_sumber_daya()
                        petugas = request.session['username']
                        tanggal = datetime.datetime.now()
                        c.execute("Set search_path to sidia;")
                        c.execute("INSERT INTO TRANSAKSI_SUMBER_DAYA VALUES({}, '{}', NULL, NULL);".format(nomor_pesanan, tanggal))
                        c.execute("INSERT INTO PESANAN_SUMBER_DAYA VALUES ({}, '{}', {});".format(nomor_pesanan, petugas, 0))
                        c.execute("INSERT INTO DAFTAR_ITEM VALUES ({}, {}, {}, '{}', NULL, NULL);".format(nomor_pesanan, no_urut, jumlah_item, kode_item))
                        
                    nomor_pesanan = generate_id_pesanan_sumber_daya()
                    petugas = request.session['username']
                    initial_data = {'no_urut': 1}

                    form = addDaftarItemForm(initial = initial_data)
                    response = {'form': form, 'id': nomor_pesanan, 'petugas': petugas}
            except:
                print("Unexpected error:", sys.exc_info()[0])
                # messages.error(request, 'PENAMBAHAN GAGAL')
                return HttpResponseRedirect(reverse('pesanansumberdaya:read_pesanansumberdaya'))
            
            print("berhasil")
            return render(request, 'create_pesanansumberdaya.html', response)
            # print("INSERT INTO KENDARAAN VALUES ({}, "{}", "{}", {});".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum))

            # try:
            #     with connection.cursor() as c:
            #         c.execute("Set search_path to sidia;")
            #         c.execute("INSERT INTO KENDARAAN VALUES ('{}', '{}', '{}', '{}');".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum))
            #         # hasil = namedtuplefetchall(c)
            # except:
            #     messages.error(request, 'PENAMBAHAN GAGAL')
            #     return HttpResponseRedirect(reverse('kendaraan:add_kendaraan'))

            

    initial_data = {'no_urut': 1}
    nomor_pesanan = generate_id_pesanan_sumber_daya()
    petugas = request.session['username']

    form = addDaftarItemForm(initial = initial_data)
    response = {'form': form, 'id': nomor_pesanan, 'petugas': petugas}
    return render(request, 'create_pesanansumberdaya.html', response)

def read_pesanansumberdaya(request):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from pesanan_sumber_daya left outer join transaksi_sumber_daya on nomor_pesanan = nomor;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        print(type(hasil[0]))
        c.execute("Set search_path to public;")
        data_pesanansumberdaya = hasil

    response = {"data_pesanansumberdaya" : data_pesanansumberdaya}
    return render(request, 'read_pesanansumberdaya.html', response)

def detail_pesanansumberdaya(request, my_id):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from pesanan_sumber_daya left outer join transaksi_sumber_daya on nomor_pesanan = nomor;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        detail_item = -1
        for item in hasil:
            if str(item.nomor) == my_id:
                detail_item = item
                break
        print(my_id)
        print(detail_item)

        c.execute("select * from daftar_item where no_transaksi_sumber_daya = %s;", my_id)
        hasil = namedtuplefetchall(c)
        print(hasil)
        daftar_pesanan = hasil
    
        kode_item = hasil[0].kode_item_sumber_daya
        c.execute("select * from item_sumber_daya where kode = '{}';".format(kode_item))
        hasil = namedtuplefetchall(c)
        print(hasil)
        itemsup = hasil[0]
        
        c.execute("Set search_path to public;")

    response = {
                "id" : my_id,
                "petugas" : detail_item.username_admin_satgas,
                "tanggal" : detail_item.tanggal,
                "username_supplier" : itemsup.username_supplier,
                "total_harga" : detail_item.total_harga,
                "daftar_pesanan_item" : daftar_pesanan}
    return render(request, 'detail_pesanansumberdaya.html', response)


def riwayat_pesanansumberdaya(request):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from item_sumber_daya;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        c.execute("Set search_path to public;")
        data_pesanansumberdaya = hasil

    response = {"data_pesanansumberdaya" : data_pesanansumberdaya}
    return render(request, 'detail_pesanansumberdaya.html', response)


def update_pesanansumberdaya(request, my_id):
    if request.method == 'POST':
        form = addKendaraanForm(request.POST)
        if form.is_valid():
            nama_kendaraan = form.cleaned_data['nama_kendaraan']
            nomor_kendaraan = form.cleaned_data['nomor_kendaraan']
            jenis_kendaraan = form.cleaned_data['jenis_kendaraan']
            berat_maksimum = form.cleaned_data['berat_maksimum']

            with connection.cursor() as c:
                c.execute("Set search_path to sidia;")
                c.execute("SELECT kode_status_batch_pengiriman, tanggal "\
                            "FROM riwayat_status_pengiriman rsp join batch_pengiriman bp "\
                            "ON bp.kode=rsp.kode_batch "\
                            "WHERE no_kendaraan='{}' "\
                            "AND rsp.kode_status_batch_pengiriman='PRO' "\
                            "OR rsp.kode_status_batch_pengiriman='OTW';".format(nomor_kendaraan))
                check = namedtuplefetchall(c)
                c.execute("Set search_path to public;")
                if len(check) == 0:
                    try:
                        c.execute("Set search_path to sidia;")
                        c.execute("UPDATE kendaraan set nomor='{}', nama='{}', jenis_kendaraan='{}', berat_maksimum='{}' "
                                  "WHERE nomor='{}';".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum, my_id))
                        c.execute("Set search_path to public;")
                        return HttpResponseRedirect(reverse('kendaraan:read_kendaraan'))
                    except:
                        messages.error(request, 'UPDATE GAGAL')
                else:
                    messages.error(request, 'UPDATE GAGAL')
                    return HttpResponseRedirect(reverse('kendaraan:update_kendaraan'))

    form = addKendaraanForm()
    response = {'form': form, 'nomor':my_id}
    return render(request, 'update_kendaraan.html', response)

def delete_pesanansumberdaya(request, my_id):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("delete from pesanan_sumber_daya where nomor_pesanan='{}';".format(my_id))
        c.execute("Set search_path to public;")

    messages.info(request, 'BERHASIL MENGHAPUS PESANAN SUMBER DAYA DENGAN NOMOR PESANAN {}'.format(my_id))
    response = {}
    return HttpResponseRedirect(reverse('pesanansumberdaya:read_pesanansumberdaya'))

pesanansumberdaya/templates/ajax_updateitembysupplier.html
{% for item in items %}
<option value="{{ item.kode }}">{{ item.kode }}</option>
{% endfor %}

pesanansumberdaya/templates/create_pesanansumberdaya.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">CREATE PESANAN SUMBER DAYA</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    <b>No Transaksi: {{ id }}</b>
    <br>
    <b>Petugas Satgas: {{ petugas }}</b>
    <br>
    <br>

    <form action='' id='createPesananForm' method="POST" class="form-group" data-supplier-url="{% url 'pesanansumberdaya:get-item-by-supplier' %}">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Tambah Item Pesanan Sumber Daya">
        </div>
    </form>
    </div>
{% endblock %}

{% block script %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script>
        $("#id_supplier").change(function () {
            const url = $("#createPesananForm").attr("data-supplier-url"); 
            const supplierUsername = $(this).val(); 

            console.log(url);
            console.log(supplierUsername);
            $.ajax({                       
                url: url,                    
                data: {
                    'supplier': supplierUsername       
                },
                success: function (data) {  
                    $("#id_kode_item").html(data);
                }
            });

        });
    </script>

{% endblock %}

pesanansumberdaya/templates/detail_pesanansumberdaya.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="jumbotron">
    <h1 class="text-center">DETAIL PESANAN SUMBER DAYA</h1>
    <br>
    
    <b>No Transaksi: {{ id }}</b>
    <br>
    <b>Petugas Satgas: {{ petugas }}</b>
    <br>
    <b>Tanggal: {{ tanggal }}</b>
    <br>
    <b>Supplier: {{ username_supplier }}</b>
    <br>
    <b>Daftar Pesanan Item: </b>
    <br>
    
    {% if daftar_pesanan_item %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th><b>No Urut</b></th>
                <th><b>Item</b></th>
                <th><b>Harga Kumulatif</b></th>
                <th><b>Jumlah Item</b></th>
            </tr>
        </thead>

        {% for pesanansumberdaya in daftar_pesanan_item %}
        <tr>
            <th>{{ pesanansumberdaya.no_urut }}</th>
            <th>{{ pesanansumberdaya.kode_item_sumber_daya }}</th>
            <th>{{ pesanansumberdaya.harga_kumulatif }}</th>
            <th>{{ pesanansumberdaya.jumlah_item }}</th>
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    <b>Total Harga: {{ total_harga }}</b>
    </div>

{% endblock %}

pesanansumberdaya/templates/read_pesanansumberdaya.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="jumbotron">
    <h1 class="text-center">READ PESANAN SUMBER DAYA</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    {% if data_pesanansumberdaya %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
              <th><b>No Pesanan</b></th>
                <th><b>Petugas Satgas</b></th>
                <th><b>Tanggal</b></th>
                <th><b>Total Berat</b></th>
                <th><b>Total Harga</b></th>
                <th><b>Status</b></th>
                {% if request.session.role == 'admin satgas' %}
                    <th><b>Action</b></th>
                {% endif %}
            </tr>
        </thead>
        {% for pesanansumberdaya in data_pesanansumberdaya %}
        <tr>
            <th>{{ pesanansumberdaya.nomor_pesanan }}</th>
            <th>{{ pesanansumberdaya.username_admin_satgas }}</th>
            <th>{{ pesanansumberdaya.tanggal }}</th>
            <th>{{ pesanansumberdaya.total_item }}</th>
            <th>{{ pesanansumberdaya.total_harga }}</th>
            <th>{{ pesanansumberdaya.status }}</th>
            {% if request.session.role == 'admin satgas' %}
                <th><a href="{% url 'pesanansumberdaya:update' my_id=pesanansumberdaya.nomor_pesanan %}"><button class="btn btn-primary" type="submit">Update</button></a>
                <a href="{% url 'pesanansumberdaya:delete' my_id=pesanansumberdaya.nomor_pesanan %}"><button class="btn btn-danger" type="submit">Delete</button></a>
                <br>
                <br>
                <a href="{% url 'pesanansumberdaya:detail' my_id=pesanansumberdaya.nomor_pesanan %}"><button class="btn btn-primary" type="submit">Detail</button></a>
                <a href="{% url 'pesanansumberdaya:delete' my_id=pesanansumberdaya.nomor_pesanan %}"><button class="btn btn-primary" type="submit">Riwayat</button></a></th>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}


    </div>
{% endblock %}

pesanansumberdaya/templates/update_pesanansumberdaya.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">UPDATE KENDARAAN {{ nomor }}</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

{#    #}
    <form action='{% url 'kendaraan:update' my_id=nomor %}' method="POST" class="form-group">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Update Kendaraan">
        </div>
    </form>
    </div>

{% endblock %}