core/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication.urls, kendaraan.urls, lokasi.urls, batch_pengiriman.urls, pesanansumberdaya.urls, stokfaskes.urls, faskes.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(authentication.urls)),
    path('',include(kendaraan.urls)),
    path('',include(lokasi.urls)),
    path('',include(batch_pengiriman.urls)),
    path('',include(pesanansumberdaya.urls)),
    path('',include(stokfaskes.urls)),
    path('',include(faskes.urls)),
]

kendaraan/urls.py
from django.urls import path
from .views import *

app_name = 'kendaraan'

urlpatterns = [
	path('kendaraan/add', add_kendaraan, name='add_kendaraan'),
	path('kendaraan/read', read_kendaraan, name='read_kendaraan'),
	path('kendaraan/update/<str:my_id>', update_kendaraan, name='update'),
	path('kendaraan/delete/<str:my_id>', delete_kendaraan, name='delete'),
]

kendaraan/models.py
from django.db import models

# Create your models here.

kendaraan/forms.py
from django import forms

kendaraan = ['Truck Telolet', 'Minibus', 'Kereta Thomas', 'Mobil', 'Kapal']

def get_jenis_kendaraan():
    result = [tuple([i, i]) for i in kendaraan]
    return result

class addKendaraanForm(forms.Form):

    nomor_kendaraan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nomor Kendaraan',
        'type' : 'text',
        'required': True,
    }))

    nama_kendaraan = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Nama Kendaraan',
        'type': 'text',
        'required': True,
    }))

    jenis_kendaraan = forms.CharField(label="jenis_kendaraan", widget=forms.Select(choices=get_jenis_kendaraan()))

    berat_maksimum = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Berat Maksimum Kendaraan (Kg)',
        'type': 'number',
        'required': True,
    }))

kendaraan/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import *

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def add_kendaraan(request):
    if request.method == 'POST':
        form = addKendaraanForm(request.POST)
        if form.is_valid():
            nama_kendaraan = form.cleaned_data['nama_kendaraan']
            nomor_kendaraan = form.cleaned_data['nomor_kendaraan']
            jenis_kendaraan = form.cleaned_data['jenis_kendaraan']
            berat_maksimum = form.cleaned_data['berat_maksimum']

            # print("INSERT INTO KENDARAAN VALUES ({}, "{}", "{}", {});".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum))

            try:
                with connection.cursor() as c:
                    c.execute("Set search_path to sidia;")
                    c.execute("INSERT INTO KENDARAAN VALUES ('{}', '{}', '{}', '{}');".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum))
                    c.execute("Set search_path to public;")
                    messages.info(request, 'PENAMBAHAN BERHASIL')
            except:
                messages.error(request, 'PENAMBAHAN GAGAL')
                return HttpResponseRedirect(reverse('kendaraan:add_kendaraan'))

            return HttpResponseRedirect(reverse('kendaraan:read_kendaraan'))

    form = addKendaraanForm()
    response = {'form': form}
    return render(request, 'add_kendaraan.html', response)

def read_kendaraan(request):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from kendaraan;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        c.execute("Set search_path to public;")
        data_kendaraan = hasil

    response = {"data_kendaraan" : data_kendaraan}
    return render(request, 'read_kendaraan.html', response)

def update_kendaraan(request, my_id):
    if request.method == 'POST':
        form = addKendaraanForm(request.POST)
        if form.is_valid():
            nama_kendaraan = form.cleaned_data['nama_kendaraan']
            nomor_kendaraan = form.cleaned_data['nomor_kendaraan']
            jenis_kendaraan = form.cleaned_data['jenis_kendaraan']
            berat_maksimum = form.cleaned_data['berat_maksimum']

            with connection.cursor() as c:
                # c.execute("Set search_path to sidia;")
                # c.execute("SELECT kode_status_batch_pengiriman, tanggal "\
                #             "FROM riwayat_status_pengiriman rsp join batch_pengiriman bp "\
                #             "ON bp.kode=rsp.kode_batch "\
                #             "WHERE no_kendaraan='{}' "\
                #             "AND rsp.kode_status_batch_pengiriman='PRO' "\
                #             "OR rsp.kode_status_batch_pengiriman='OTW';".format(nomor_kendaraan))
                # check = namedtuplefetchall(c)
                # c.execute("Set search_path to public;")
                if check_status_available(my_id):
                    try:
                        c.execute("Set search_path to sidia;")
                        c.execute("UPDATE kendaraan set nomor='{}', nama='{}', jenis_kendaraan='{}', berat_maksimum='{}' "
                                  "WHERE nomor='{}';".format(nomor_kendaraan, nama_kendaraan, jenis_kendaraan, berat_maksimum, my_id))
                        c.execute("Set search_path to public;")
                        messages.info(request, 'BERHASIL MENGUPDATE KENDARAAN {}'.format(my_id))
                        return HttpResponseRedirect(reverse('kendaraan:read_kendaraan'))
                    except:
                        messages.error(request, 'UPDATE GAGAL')
                else:
                    messages.error(request, 'KENDARAAN TIDAK AVAILABLE')
                    return HttpResponseRedirect(reverse('kendaraan:update_kendaraan'))

    form = addKendaraanForm()
    response = {'form': form, 'nomor':my_id}
    return render(request, 'update_kendaraan.html', response)

def delete_kendaraan(request, my_id):

    if check_status_available(my_id):
        with connection.cursor() as c:
            c.execute("Set search_path to sidia;")
            c.execute("delete from kendaraan where nomor='{}';".format(my_id))
            c.execute("Set search_path to public;")
            messages.info(request, 'BERHASIL MENGHAPUS KENDARAAN {}'.format(my_id))
    else:
        messages.error(request, 'GAGAL MENGHAPUS KENDARAAN {}'.format(my_id))

    response = {}
    return HttpResponseRedirect(reverse('kendaraan:read_kendaraan'))

def check_status_available(nomor_kendaraan):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT kode_status_batch_pengiriman " \
                  "FROM riwayat_status_pengiriman rsp join batch_pengiriman bp " \
                  "ON bp.kode=rsp.kode_batch " \
                  "WHERE no_kendaraan='{}' "\
                  "ORDER BY tanggal DESC LIMIt 1;".format(nomor_kendaraan))
        check = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        print(check)

    if len(check)==0:
        return True
    if check[0].kode_status_batch_pengiriman == "OTW" and check[0].kode_status_batch_pengiriman == "PRO":
        return False
    return True

kendaraan/templates/add_kendaraan.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">ADD KENDARAAN</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}


    <form action='' method="POST" class="form-group">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Tambah Kendaraan">
        </div>
    </form>
    </div>

{% endblock %}

kendaraan/templates/read_kendaraan.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="jumbotron">
    <h1 class="text-center">LIST KENDARAAN</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    {% if data_kendaraan %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
{#                <th><b>No</b></th>#}
                <th><b>No Kendaraan</b></th>
                <th><b>Nama Kendaraan</b></th>
                <th><b>Jenis Kendaraan</b></th>
                <th><b>Berat Max (Kg)</b></th>
                {% if request.session.role == 'admin satgas' %}
                    <th><b>Action</b></th>
                {% endif %}
            </tr>
        </thead>
        {% for kendaraan in data_kendaraan %}
        <tr>
            <th>{{ kendaraan.nomor }}</th>
            <th>{{ kendaraan.nama }}</th>
            <th>{{ kendaraan.jenis_kendaraan }}</th>
            <th>{{ kendaraan.berat_maksimum }}</th>
            {% if request.session.role == 'admin satgas' %}
                <th><a href="{% url 'kendaraan:update' my_id=kendaraan.nomor %}"><button class="btn btn-primary" type="submit">Update</button></a>
                <a href="{% url 'kendaraan:delete' my_id=kendaraan.nomor %}"><button class="btn btn-danger" type="submit">Delete</button></a></th>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}


    </div>
{% endblock %}

kendaraan/templates/update_kendaraan.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">UPDATE KENDARAAN {{ nomor }}</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

{#    #}
    <form action='{% url 'kendaraan:update' my_id=nomor %}' method="POST" class="form-group">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Update Kendaraan">
        </div>
    </form>
    </div>

{% endblock %}