core/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication.urls, kendaraan.urls, lokasi.urls, batch_pengiriman.urls, pesanansumberdaya.urls, stokfaskes.urls, faskes.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(authentication.urls)),
    path('',include(kendaraan.urls)),
    path('',include(lokasi.urls)),
    path('',include(batch_pengiriman.urls)),
    path('',include(pesanansumberdaya.urls)),
    path('',include(stokfaskes.urls)),
    path('',include(faskes.urls)),
]

stokfaskes/urls.py
from django.urls import path
from .views import *

app_name = 'stokfaskes'

urlpatterns = [
    path('stokfaskes/create', create_stokfaskes, name='create_stokfaskes'),
	path('stokfaskes/read', read_stokfaskes, name='read_stokfaskes'),
	path('stokfaskes/update/<str:my_id>', update_stokfaskes, name='update'),
	path('stokfaskes/delete/<str:my_id>', delete_stokfaskes, name='delete'),
]

stokfaskes/models.py
from django.db import models

# Create your models here.

stokfaskes/forms.py
from django import forms

kode = ['113639894287', '143089766565', '274987649790', '821946242720', '612034310135', '113639894287', '143089766565', '274987649790', '821946242720', '612034310135']
item = ['ITM1', 'ITM2', 'ITM3', 'ITM4', 'ITM5', 'ITM6', 'ITM7', 'ITM8', 'ITM9', 'ITM10']

def get_kode():
    result = [tuple([i, i]) for i in kode]
    return result

def get_item():
    result = [tuple([i, i]) for i in item]
    return result

class createStok(forms.Form):

    kode_faskes = forms.CharField(label="kode_faskes", widget=forms.Select(choices=get_kode()))

    kode_item = forms.CharField(label="kode_item", widget=forms.Select(choices=get_item()))

    jumlah = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Jumlah',
        'type': 'number',
        'required': True,
    }))

stokfaskes/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import *

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def create_stokfaskes(request):
    if request.method == 'POST':
        form = createStok(request.POST)
        if form.is_valid():
            kode_faskes = form.cleaned_data['kode_faskes']
            kode_item = form.cleaned_data['kode_item']
            jumlah = form.cleaned_data['jumlah']

            try:
                with connection.cursor() as c:
                    c.execute("Set search_path to sidia;")
                    c.execute("UPDATE STOK_FASKES SET JUMLAH ('{}', '{}', '{}');".format(kode_faskes, kode_item, jumlah))
                    c.execute("Set search_path to public;")
                    messages.info(request, 'PENAMBAHAN BERHASIL')
            except:
                messages.error(request, 'PENAMBAHAN GAGAL')
                return HttpResponseRedirect(reverse('stokfaskes:create_stokfaskes'))

            return HttpResponseRedirect(reverse('stokfaskes:read_stokfaskes'))

    form = createStok()
    response = {'form': form}
    return render(request, 'create_stokfaskes.html', response)

def read_stokfaskes(request):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from stok_faskes;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        c.execute("Set search_path to public;")
        data_stokfaskes = hasil

    response = {"data_stokfaskes" : data_stokfaskes}
    return render(request, 'read_stokfaskes.html', response)

def detail_pesanansumberdaya(request, my_id):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("select * from pesanan_sumber_daya left outer join transaksi_sumber_daya on nomor_pesanan = nomor;")
        hasil = namedtuplefetchall(c)
        print(hasil)
        detail_item = -1
        for item in hasil:
            if str(item.nomor) == my_id:
                detail_item = item
                break
        print(my_id)
        print(detail_item)

        c.execute("select * from daftar_item where no_transaksi_sumber_daya = %s;", my_id)
        hasil = namedtuplefetchall(c)
        print(hasil)
        daftar_pesanan = hasil
    
        kode_item = hasil[0].kode_item_sumber_daya
        c.execute("select * from item_sumber_daya where kode = '{}';".format(kode_item))
        hasil = namedtuplefetchall(c)
        print(hasil)
        itemsup = hasil[0]
        
        c.execute("Set search_path to public;")

    response = {
                "id" : my_id,
                "petugas" : detail_item.username_admin_satgas,
                "tanggal" : detail_item.tanggal,
                "username_supplier" : itemsup.username_supplier,
                "total_harga" : detail_item.total_harga,
                "daftar_pesanan_item" : daftar_pesanan}
    return render(request, 'detail_pesanansumberdaya.html', response)

def update_stokfaskes(request, my_id):
    with connection.cursor() as c:
                c.execute("Set search_path to sidia;")
                c.execute("select * from stok_faskes where kode_faskes = '{}';".format(my_id))
                hasil = namedtuplefetchall(c)
                print(hasil)
                daftar_stok = -1
                for item in hasil:
                    if str(item.kode_faskes) == my_id:
                        daftar_stok = item
                        break

    if request.method == 'POST':
        form = updateStok(request.POST)
        if form.is_valid():
            jumlahbaru = form.cleaned_data['jumlah']
            with connection.cursor() as c:
                if check_status_available(my_id):
                    try:
                        c.execute("UPDATE stok_faskes set jumlah = {} WHERE kode_faskes='{}';".format(jumlahbaru, my_id))
                        c.execute("Set search_path to public;")
                        messages.info(request, 'BERHASIL MENGUPDATE KENDARAAN {}'.format(my_id))
                        return HttpResponseRedirect(reverse('stokfaskes:read_stokfaskes'))
                    except:
                        messages.error(request, 'UPDATE GAGAL')
                else:
                    messages.error(request, 'KENDARAAN TIDAK AVAILABLE')
                    return HttpResponseRedirect(reverse('stokfaskes:update_stokfaskes'))

    form = updateStok()
    response = {'form': form, 
                'kode_faskes':my_id,
                'id':daftar_stok.kode_faskes,
                'item':daftar_stok.kode_item_sumber_daya}
    return render(request, 'update_stokfaskes.html', response)

def delete_stokfaskes(request, my_id):

    if check_status_available(my_id):
        with connection.cursor() as c:
            c.execute("Set search_path to sidia;")
            c.execute("delete from stok_faskes where kode_faskes='{}';".format(my_id))
            c.execute("Set search_path to public;")
            messages.info(request, 'BERHASIL MENGHAPUS STOK {}'.format(my_id))
    else:
        messages.error(request, 'GAGAL MENGHAPUS STOK {}'.format(my_id))

    response = {}
    return HttpResponseRedirect(reverse('stokfaskes:read_stokfaskes'))

def check_status_available(nomor_kendaraan):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT kode_status_batch_pengiriman " \
                  "FROM riwayat_status_pengiriman rsp join batch_pengiriman bp " \
                  "ON bp.kode=rsp.kode_batch " \
                  "WHERE no_kendaraan='{}' "\
                  "ORDER BY tanggal DESC LIMIt 1;".format(nomor_kendaraan))
        check = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        print(check)

    if len(check)==0:
        return True
    if check[0].kode_status_batch_pengiriman == "OTW" and check[0].kode_status_batch_pengiriman == "PRO":
        return False
    return True

stokfaskes/templates/create_stokfaskes.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">ADD KENDARAAN</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}


    <form action='' method="POST" class="form-group">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Tambah Kendaraan">
        </div>
    </form>
    </div>

{% endblock %}

stokfaskes/templates/read_stokfaskes.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="jumbotron">
    <h1 class="text-center">LIST KENDARAAN</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    {% if data_stokfaskes %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th><b>Kode Faskes</b></th>
                <th><b>Kode Item Sumber Daya</b></th>
                <th><b>Jumlah</b></th>
                <th><b>Action</b></th>
            </tr>
        </thead>
        {% for data in data_stokfaskes %}
        <tr>
            <th>{{ data.kode_faskes }}</th>
            <th>{{ data.kode_item_sumber_daya }}</th>
            <th>{{ data.jumlah }}</th>
            {% if request.session.role == 'admin satgas' %}
                <th><a href="{% url 'stokfaskes:update' my_id=data.kode_faskes %}"><button class="btn btn-primary" type="submit">Update</button></a>
                <a href="{% url 'stokfaskes:delete' my_id=data.kode_faskes %}"><button class="btn btn-danger" type="submit">Delete</button></a></th>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}


    </div>
{% endblock %}

stokfaskes/templates/update_stokfaskes.html
{% extends 'navbar.html' %}

{% block content %}
    <div class="jumbotron">
    <h1 class="text-center">UPDATE STOK FASKES</h1>
    <br>
    
    <b>Kode Faskes: {{ id }}</b>
    <br>
    <b>Item: {{ item }}</b>
    <br>
    <br>
    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

{#    #}
    <form action='{% url 'stokfaskes:update' my_id=kode_faskes %}' method="POST" class="form-group">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Update Stok Faskes">
        </div>
    </form>
    </div>

{% endblock %}