batch_pengiriman/urls.py
from django.urls import path
from .views import *

app_name = 'batch_pengiriman'

urlpatterns = [
	path('batch', read_batch, name='read_batch'),
	path('batch/tambah', tambah_batch, name='tambah_batch'),
	path('batch/create/<str:my_id>/<str:nama>', create_batch, name='create_batch'),
	# path('lokasi/update/<str:my_id>', update_lokasi, name='update_lokasi'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
import authentication.urls, kendaraan.urls, lokasi.urls, batch_pengiriman.urls, pesanansumberdaya.urls, stokfaskes.urls, faskes.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(authentication.urls)),
    path('',include(kendaraan.urls)),
    path('',include(lokasi.urls)),
    path('',include(batch_pengiriman.urls)),
    path('',include(pesanansumberdaya.urls)),
    path('',include(stokfaskes.urls)),
    path('',include(faskes.urls)),
]

batch_pengiriman/models.py
from django.db import models

# Create your models here.

batch_pengiriman/forms.py
from django import forms
from django.db import connection
from collections import namedtuple

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def generate_lokasi():
    result = []
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT id FROM lokasi ORDER BY id ASC;")
        data_id = namedtuplefetchall(c)
        c.execute("Set search_path to public;")

        for id in data_id:
            result.append(id.id)

    return result

def generate_kendaraan():
    result = []
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT nomor FROM kendaraan;")
        data_id = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        for id in data_id:
            result.append(id.nomor)
    return result

def generate_petugas_distribusi():
    result = []
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT username FROM petugas_distribusi;")
        data_id = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        for id in data_id:
            result.append(id.username)
    return result

def get_lokasi():
    result = [tuple([i, i]) for i in generate_lokasi()]
    return result

def get_kendaraan():
    result = [tuple([i, i]) for i in generate_kendaraan()]
    return result

def get_petugas():
    result = [tuple([i, i]) for i in generate_petugas_distribusi()]
    return result



class createBatchForm(forms.Form):
    kendaraan = forms.CharField(label="Kendaraan", widget=forms.Select(choices=get_kendaraan()))
    petugas = forms.CharField(label="Petugas Distribusi", widget=forms.Select(choices=get_petugas()))

    asal = forms.CharField(label="Lokasi Asal Pengiriman", widget=forms.Select(choices=get_lokasi()))

    tujuan = forms.CharField(label="Lokasi Tujuan Pengiriman", widget=forms.Select(choices=get_lokasi()))

batch_pengiriman/views.py
from django.shortcuts import render
from django.db import connection
from collections import namedtuple
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from .forms import *

def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]

def toList(list_tuple):
    result = []
    for tuple in list_tuple:
        kamus = dict()
        kamus["no_transaksi_sumber_daya"] = tuple.no_transaksi_sumber_daya
        kamus['nama'] = tuple.nama
        kamus['id_lokasi'] = tuple.id_lokasi
        kamus['total_berat'] = tuple.total_berat
        kamus['status_permohonan'] = tuple.status_permohonan[-3:]
        if tuple.status_pengiriman:
            kamus['status_pengiriman'] = tuple.status_pengiriman[-3:]
        result.append(kamus)
    return result


def read_batch(request):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("""select Distinct no_transaksi_sumber_daya, nama, id_lokasi, total_berat, string_agg(kode_status_permohonan, ', '
                    ORDER BY rsp.tanggal) status_permohonan, string_agg(kode_status_batch_pengiriman, ', ' ORDER BY sp.tanggal) status_pengiriman
                    FROM permohonan_sumber_daya_faskes psdf join pengguna p
                    ON psdf.username_petugas_faskes=p.username
                    JOIN faskes f ON f.username_petugas=psdf.username_petugas_faskes
                    JOIN transaksi_sumber_daya tsd ON tsd.nomor=psdf.no_transaksi_sumber_daya
                    LEFT JOIN riwayat_status_permohonan rsp ON rsp.nomor_permohonan=psdf.no_transaksi_sumber_daya
                    JOIN batch_pengiriman bp ON tsd.nomor=bp.nomor_transaksi_sumber_daya
                    LEFT JOIN riwayat_status_pengiriman sp ON sp.kode_batch=bp.kode
                    GROUP BY no_transaksi_sumber_daya, nama, id_lokasi, total_berat
                    ORDER BY no_transaksi_sumber_daya ASC;""")
        hasil = namedtuplefetchall(c)
        # print(hasil)
        c.execute("Set search_path to public;")
        data_batch = toList(hasil)

    response = {"data_batch": data_batch}
    return render(request, "read_batch.html", response)

def generate_kode_bp():
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT kode FROM batch_pengiriman ORDER BY kode DESC LIMIT 1;")
        last_id = namedtuplefetchall(c)
        c.execute("Set search_path to public;")
        if len(last_id) == 0:
            return "bp001"
        number = last_id[0].kode.split("bp")

    return "bp{0:03d}".format((int(number[1]) + 1))

def generat_alamat(id):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("""SELECT provinsi, kabkot, kecamatan, kelurahan, jalan_no
        FROM lokasi
        WHERE id='{}';""".format(id))
        hasil = namedtuplefetchall(c)
        c.execute("Set search_path to public;")

        if hasil:
            return "{}, {}, {}, {}, {}".format(hasil[0].provinsi, hasil[0].kabkot, hasil[0].kecamatan, hasil[0].kelurahan, hasil[0].jalan_no)

    return "Lokasi tidak ada"

def get_username(nama):
    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("SELECT username from pengguna where nama='{}';".format(nama))
        hasil = namedtuplefetchall(c)
        c.execute("Set search_path to public;")

        if len(hasil) == 1:
            return hasil[0].username

    return "username tidak ditemukan"

def create_batch(request, my_id, nama):
    if request.method == 'POST':
        form = createBatchForm(request.POST)
        if form.is_valid():
            kode = generate_kode_bp()
            no = my_id
            satgas = get_username(nama)

            supir = form['petugas'].value()
            kendaraan = form['kendaraan'].value()

            asal = form['asal'].value()
            tujuan = form['tujuan'].value()
            tanda_terima = "Diterima"

            with connection.cursor() as c:
                c.execute("Set search_path to sidia;")
                c.execute("""INSERT INTO batch_pengiriman values
                ('{}','{}','{}','{}','{}','{}','{}','{}');""".format(kode, satgas, supir, tanda_terima, no, asal, tujuan, kendaraan))
                c.execute("Set search_path to public;")

    with connection.cursor() as c:
        c.execute("Set search_path to sidia;")
        c.execute("""SELECT kode, k.nama as kendaraan, p.nama as petugas, id_lokasi_asal, id_lokasi_tujuan
        FROM batch_pengiriman bp JOIN pengguna p ON username=username_petugas_distribusi
        JOIN kendaraan k ON bp.no_kendaraan=k.nomor
        WHERE nomor_transaksi_sumber_daya='{}';""".format(my_id))
        hasil = namedtuplefetchall(c)
        c.execute("Set search_path to public;")

    form = createBatchForm()
    response = {"form" : form, "kode_bp": generate_kode_bp(), "no":my_id, "nama":nama, "data_batch_tentu":hasil}
    return render(request, "create_batch.html", response)

def tambah_batch(request):

    return HttpResponseRedirect(reverse('batch_pengiriman:read_batch'))

batch_pengiriman/templates/create_batch.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">FORM BATCH PENGIRIMAN {{ no }}</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    <form action='{% url 'batch_pengiriman:create_batch' my_id=no nama=nama %}' method="POST" class="form-group">
        {% csrf_token %}
        <div class="form-group">
        <label for="petugas_satgas">Petugas Satgas:</label>
        <input type="text" class="form-control" disabled value="{{ nama }}" name="petugas_satgas" id="petugas_satgas">
        </div>

        <div class="form-group">
        <label for="no">Nomor Transaksi Sumber Daya:</label>
        <input type="text" class="form-control" disabled value="{{ no }}" name="no" id="no">
        </div>

        <p>Buat Batch Pengiriman:</p>
        <div class="form-group">
        <label for="kode">Kode Batch:</label>
        <input type="text" class="form-control" disabled value="{{ kode_bp }}" name="kode" id="kode">
        </div>

        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.label_tag }} {{ field }}
        </div>
        {% endfor %}
        <div class="centre-items">
            <input type="submit" class="btn btn-primary" value="Tambah Batch">
        </div>
    </form>

    <br>
    <p>Daftar Batch Pengiriman</p>
    <table class="table">
        <thead class="thead-dark">
            <tr>
{#                <th><b>No</b></th>#}
                <th><b>Kode Batch</b></th>
                <th><b>Kendaraan</b></th>
                <th><b>Petugas Distribusi</b></th>
                <th><b>Asal</b></th>
                <th><b>Tujuan</b></th>
            </tr>
        </thead>
        {% for batch in data_batch_tentu %}
        <tr>
            <th>{{ batch.kode }}</th>
            <th>{{ batch.kendaraan }}</th>
            <th>{{ batch.petugas }}</th>
            <th>{{ batch.id_lokasi_asal }}</th>
            <th>{{ batch.id_lokasi_tujuan }}</th>
        </tr>
        {% endfor %}
    </table>


    </div>

{% endblock %}

batch_pengiriman/templates/read_batch.html
{% extends 'navbar.html' %}

{% block content %}

    <div class="jumbotron">
    <h1 class="text-center">BATCH PENGIRIMAN</h1>
    <br>

    {% if messages %}
        {% for message in messages %}
            <p{% if message.tags %} class="{{ message.tags }} alert alert-danger" role="alert"{% endif %}>{{ message }}</p>
        {% endfor %}
    {% endif %}

    {% if data_batch %}
    <table class="table">
        <thead class="thead-dark">
            <tr>
{#                <th><b>No</b></th>#}
                <th><b>No. Transaksi</b></th>
                <th><b>Petugas Faskes</b></th>
                <th><b>Faskes</b></th>
                <th><b>Total Berat (Kg)</b></th>
                <th><b>Status Permohonan</b></th>
                <th><b>Status Batch</b></th>
                {% if request.session.role == 'admin satgas' %}
                    <th><b>Action</b></th>
                {% endif %}
            </tr>
        </thead>
        {% for batch in data_batch %}
        <tr>
            <th>{{ batch.no_transaksi_sumber_daya }}</th>
            <th>{{ batch.nama }}</th>
            <th>Faskes {{ batch.id_lokasi }}</th>
            <th>{{ batch.total_berat }}</th>
            <th>{{ batch.status_permohonan }}</th>
            <th>
                {% if batch.status_pengiriman %}
                    {{ batch.status_pengiriman }}
                {% endif %}
            </th>
            {% if batch.status_permohonan == 'PRO' %}
                <th><a href="{% url 'batch_pengiriman:create_batch' my_id=batch.no_transaksi_sumber_daya nama=batch.nama %}"><button class="btn btn-primary" type="submit">Buat Batch</button></a></th>
            {% elif batch.status_permohonan == "FIN" or batch.status_permohonan == "MAS" %}
                <th><a href="{% url 'batch_pengiriman:create_batch' my_id=batch.no_transaksi_sumber_daya nama=batch.nama %}"><button class="btn btn-success" type="submit">Detail</button></a></th>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% endif %}

    </div>

{% endblock %}